sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IrndZVUQpH1pnfMzx0yNxfxSPybKP2GwU6BZN6GlC/eXd2q8urOM2PnCeeN7UUt70BY8tY/U2UxIMUfaUoGSa0ljQLtO1gXPO6gLMZ7IRaWpqZwDCN5RBuBDCzjyTPh4XBauQSA8bJM3Qo2gceJNIO3uWXjsgJL48X+LO28VX+ppus821EUuc0kh7M+YnOqadOixcdv2YoNZsaDNlE4acpzYu4NinHScl89VarQlvfE2kRTgQz+/eIIzGUf60NU4xnyjFPwbq6aqDU45qAmc273pAJlbOtBIspgtILJ54Lhg0/nvprmFDGtlSG8mtmA2LyYpfJogqSknGDvcTekauZjOlChCzUVr7TzNrU6mTt/CL+D078Jxlxobl2JbCYhKAVo5uVUqquwMt7HDan3fDLhuV/tmrkXpjqBf8JvakwFZW+i+0WGVrMuR7IvQT1NBSGjqT7QFk+SDCuRPUhVcITktg95uVIQwPS33khaPyYpovX7yRDqd9DCjVNXLjLGk6OcK9VoHYNn5UIgrGpWV42Va2RncPr73r3qAcUuI/vJipfXU8H3cRthsvXo7rXMhF7QXcHEVeny1uJ6k/uZTftgsInzz2usEDv8eIPrv92nQqHIBM2nqfu3cKu0/ANxouKRcOgzPsE/nTLL/ACXOVWAdKxtlr9D8NmzHFYMvL3s=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-History-of-Science---Volume-2_1706
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy